language: python
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install .
script: python setup.py test
deploy:
  skip_cleanup: true
  provider: script
  script: make travis-docker-push
  on:
    branch: master
